### ISSUE TITLE
Not working on ff 57 or ff56

### ISSUE THREAD

**Issue by xLink** [itsgoingd/clockwork-firefox#4]
verified working in chrome, but the addon wont work in ff 56 or 57(ff dev), no idea how to debug this..

checked via the web UI, getting the same info back in chrome's version of the extension as the web ui..

**Comment by itsgoingd** [comment]
Hey, try going to `about:debugging`, find Clockwork in the list, click on "Debug" - this will launch developer tools window for the extension - see if there are any relevant errors in the console tab or if any pop up when you try to use it.

**Comment by miclf** [comment]
Hi,

I have a similar issue, it doesn’t seem to work (Firefox 57.0b12).

The Clockwork panel does appear in devtools but just shows an empty request subpanel. There is no other subpanel. Here is a screenshot.

![clockwork](https://user-images.githubusercontent.com/3188746/32228100-a1461aae-be4d-11e7-9f34-dce4b208cff3.png)


Browsing the site while keeping the clockwork panel open doesn’t change anything. The Web UI, however, works like a charm.

Running debug in `about:debugging` doesn’t show any error… Is there any other way to obtain potential feedback in order to report it here?

**Comment by itsgoingd** [comment]
Hey, looks like this is a bug in Firefox 57 that is fixed in the latest 58 beta.

If you decide to try out the beta let me know if it fixes the issue for you.

**Comment by miclf** [comment]
I confirm it works on Firefox 58.0b4 🍾 

A few details apart, the experience is the same as the one in the Web UI.

@itsgoingd do you know which Firefox/Gecko bug was causing the issue? I’d be interested in having a look to it.

**Comment by itsgoingd** [comment]
We are [capturing all HTTP requests](https://github.com/itsgoingd/clockwork-firefox/blob/master/Clockwork%20Firefox/assets/javascripts/chrome/background.js#L58-L67) via the `browser.webRequest.onCompleted` api, sending them to the Clockwork dev tools app.

Here we [check if the `request.tabId` matches inspected tab's id](https://github.com/itsgoingd/clockwork-firefox/blob/master/Clockwork%20Firefox/assets/javascripts/extension.js#L65), to only show requests from tab that has the dev tools window open.

In Firefox 57 the `request.tabId` is always returned as -1 (this should normally be case only for HTTP requests with no tab associated), which means no requests will pass the check and no data will be shown.

We can fix this temporarily simply by commenting out that check, everything else works fine. I'm not familiar with Firefox release schedule, is it worth doing so or shall we wait for the 58 release?

**Comment by miclf** [comment]
Thanks for these details!

Unless I’m wrong, Firefox and Chrome have exactly the same intervals of time between two releases: about 6 weeks.

Firefox 57 was released last week and, according to [this schedule](https://wiki.mozilla.org/RapidRelease/Calendar), version 58 should ship on 2018-01-23. On the one hand, I guess it could be useful to release a bugfix for v57. On the other end, developers are encouraged to use the [Developer Edition](https://www.mozilla.org/fr/firefox/developer/) of Firefox, and this one is already built from the v58 branch, meaning that Clockwork work as expected with it (I’m using it right now).

**Comment by miclf** [comment]
I’ve just seen that you released a bugfix in v2.0.2 of the extension. This makes my previous comment rather obsolete, I guess :-)

**Comment by itsgoingd** [comment]
Yeah, didn't want to leave this broken for 2 more months and I realised we can easily check and apply the workaround only for the problematic Firefox version.

Didn't know about the Developer Edition using the latest beta, good to know. :)

**Comment by miclf** [comment]
Yep, the Dev Edition is always one version ahead of the released one. As such, it allows to test and play with upcoming changes and APIs (it used to be called ‘Aurora’ version in the past, since it was between nightlies and stable releases).
